FROM node:16.20.2

ARG USERNAME=node

LABEL maintainer=hoahoanganh20012001@gmail.com

COPY setups/* /root/

# RUN chmod +x docker-custom-entrypoint.sh
# RUN bash /tmp/setups/bash-custom.sh

# ENTRYPOINT ["/docker-custom-entrypoint.sh"]

CMD ["bash"]