name: node
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version deploy."
        required: true
jobs:
  v16:
    runs-on: ubuntu-latest
    name: v16
    if: ${{ (github.event.inputs.version == '16') || (github.event.inputs.version == 'node') || (github.event.inputs.version == '*') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.DOCKER_REPO }}
          token: ${{ secrets.GH_TOKEN }}
          path: .
          sparse-checkout: images

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and publish
        uses: docker/build-push-action@v3
        with:
          context: ./images/node
          file: ./images/node/Dockerfile-16
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/node:16
          build-args: GITHUB_TOKEN=${{ secrets.GH_TOKEN }}
